#!/usr/bin/env python3

from random import randrange, choice

def main():
    n = 2 * 10**5
    s = ''.join([choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ') for i in range(2 * n)])
    print(n)
    print(s)
    q = 1
    print(q)
    print(1, 1, 2)

main()
