#!/usr/bin/env python3

alpha = 'abcdefghijklmnopqrstuvwxyz'               
cnt = 0
for i in alpha:
    for j in alpha:
        for k in alpha:
            s = i + j + k
            if "ab" in s and not "c" in s:
                cnt += 1
print(cnt)
