#!/usr/bin/env python3

import sys, re

def main():
    N = 200000
    vec = [0] * N
    vec[0] = int(sys.argv[1])
    vec[1] = int(sys.argv[2])
    n = int(input())
    for i in range(n):
        line = input().strip()
        (opc, rest) = line.split(maxsplit=1)
        if opc == '<' or opc == '+':
            (si, sj, sk) = rest.split()
            (i,j,k) = map(int, [si,sj,sk])
            if opc == '<':
                vec[k] = 1 if vec[i] < vec[j] else 0
            else:
                vec[k] = vec[i] + vec[j]
        elif opc == 'D':
            mo = re.match(r"\s*'(.*)'\s*(.*)", rest)
            msg = mo[1]
            vs = map(int, mo[2].split())
            print(msg, end=' ');
            for v in vs:
                print(f'vec[{v}] = {vec[v]}', end = ' ')
            print()
        else:
            assert(0)
    print(vec[2])

main()
