#!/usr/bin/env python3

def main():
    L = 10**14
    mlen = 25
    vec = []
    p = 1
    sum = 0
    while True:
        if sum + p > 200:
            break
        vec.append('a' * p)
        sum += p
        if p == mlen:
            p = 1
        else:
            p += 1
    
    print(len(vec), L)
    print(' '.join(['1' for s in vec]))
    for s in vec:
        print(s)

main()
