cp t/test_out/1_sample_1.txt dexp_y1.txt
cp t/test_out/1_sample_2.txt dexp_y2.txt
cp t/test_out/1_sample_3.txt dexp_y3.txt
cp t/test_out/2_small_1.txt dexp_y4.txt
cp t/test_out/2_small_2.txt dexp_y5.txt
cp t/test_out/2_small_3.txt dexp_y6.txt
cp t/test_out/2_small_4.txt dexp_y7.txt
cp t/test_out/2_small_5.txt dexp_y8.txt
cp t/test_out/3_large_1.txt dexp_y9.txt
cp t/test_out/3_large_10.txt dexp_y10.txt
cp t/test_out/3_large_11.txt dexp_y11.txt
cp t/test_out/3_large_12.txt dexp_y12.txt
cp t/test_out/3_large_13.txt dexp_y13.txt
cp t/test_out/3_large_14.txt dexp_y14.txt
cp t/test_out/3_large_15.txt dexp_y15.txt
cp t/test_out/3_large_2.txt dexp_y16.txt
cp t/test_out/3_large_3.txt dexp_y17.txt
cp t/test_out/3_large_4.txt dexp_y18.txt
cp t/test_out/3_large_5.txt dexp_y19.txt
cp t/test_out/3_large_6.txt dexp_y20.txt
cp t/test_out/3_large_7.txt dexp_y21.txt
cp t/test_out/3_large_8.txt dexp_y22.txt
cp t/test_out/3_large_9.txt dexp_y23.txt
cp t/test_out/4_max_1.txt dexp_y24.txt
cp t/test_out/4_max_10.txt dexp_y25.txt
cp t/test_out/4_max_2.txt dexp_y26.txt
cp t/test_out/4_max_3.txt dexp_y27.txt
cp t/test_out/4_max_4.txt dexp_y28.txt
cp t/test_out/4_max_5.txt dexp_y29.txt
cp t/test_out/4_max_6.txt dexp_y30.txt
cp t/test_out/4_max_7.txt dexp_y31.txt
cp t/test_out/4_max_8.txt dexp_y32.txt
cp t/test_out/4_max_9.txt dexp_y33.txt
cp t/test_out/5_kill_1.txt dexp_y34.txt
cp t/test_out/5_kill_2.txt dexp_y35.txt
cp t/test_out/5_kill_3.txt dexp_y36.txt
cp t/test_out/6_kill_1.txt dexp_y37.txt
cp t/test_out/6_kill_2.txt dexp_y38.txt
cp t/test_out/6_kill_3.txt dexp_y39.txt
