#!/usr/bin/env python3

import argparse, sys
from random import randrange, choice

# Function generate() should yield test cases of type string repeatedly.
# E.g.,
#    def generate():
#        for x in range(1, 10):
#            for cdir in ['N', 'E', 'S', 'W']:
#                yield f'{x}\n{cdir}\n'
# or E.g.,
#    def generate():
#        while True:
#            x = randrange(1, 10)
#            cdir = choice(['N', 'E', 'S', 'W'])
#            case = f'''{x}
#    {cdir}
#    '''
#            yield case

def generate():
    while True:
        N = 10
        Q1 = 10
        Q2 = 4
        case = f'{N} {Q1+Q2}\n'
        for i in range(Q1):
            x = randrange(1, N+1)
            y = randrange(1, N+1)
            z = randrange(1, 3)
            case += f'1 {x} {y} {z}\n'
        for i in range(Q2):
            x = randrange(1, N+1)
            y = randrange(1, N+1)
            case += f'2 {x} {y} 1\n'
        yield case

######################################################################
# Hope that you need not edit the following code.

end_mark = '^__=end=__^'
end_file_mark = '^__=end_file=__^'

def main():
    ap = argparse.ArgumentParser();
    ap.add_argument('-r', '--repeat', action='store_true',
                    help='Repeatedly generates cases',)
    args = ap.parse_args()

    try:
        if args.repeat:
            for s in generate():
                print(s.rstrip())
                print(end_mark)
            print(end_file_mark)
        else:
            for (i, s) in enumerate(generate()):
                print(s.rstrip())
                print(end_mark)
                if (i == 4):
                    break
    except BrokenPipeError as e:
        # print('caught: BrokenPipeError', file=sys.stderr)
        pass

main()
