#!/usr/bin/env python3

# This code was generated by ChatGPT 4

def main():
    import sys
    input = sys.stdin.read
    data = input().split()
    
    R = int(data[0])
    C = int(data[1])
    K = int(data[2])
    N = int(data[3])
    
    candies = []
    row_candies = [0] * R
    col_candies = [0] * C
    
    index = 4
    for _ in range(N):
        r = int(data[index]) - 1
        c = int(data[index + 1]) - 1
        candies.append((r, c))
        row_candies[r] += 1
        col_candies[c] += 1
        index += 2
    
    # Count how many rows and columns have specific number of candies
    row_count = [0] * (N + 1)
    col_count = [0] * (N + 1)
    
    for count in row_candies:
        row_count[count] += 1
    for count in col_candies:
        col_count[count] += 1
    
    # Calculate the total positions that meet the criteria
    result = 0
    for i in range(N + 1):
        if K - i >= 0 and K - i <= N:
            result += row_count[i] * col_count[K - i]
    
    # Adjust for the overcounting where candies lie on the same cell
    for r, c in candies:
        total_candies = row_candies[r] + col_candies[c]
        if total_candies == K:
            result -= 1
        elif total_candies == K + 1:
            result += 1
    
    print(result)

if __name__ == "__main__":
    main()
