#!/usr/bin/env python3

import sys
from random import randrange

def main():
    n = int(sys.argv[1])
    q = int(sys.argv[2])
    print(n)
    lst = [randrange(1, n + 1) for i in range(n)]
    print(' '.join(map(str, lst)))
    print(q)
    for i in range(q):
        x = randrange(1, n + 1)
        y = randrange(1, n + 1)
        if x > y:
            x, y = y, x
        print(x, y)

main()
