#!/usr/bin/env python3

from random import randrange

def main():
    n = int(9e4)
    q = int(9e5)
    print(n)
    lst = [randrange(1, n + 1) for i in range(n)]
    print(' '.join(map(str, lst)))
    print(q)
    for i in range(q):
        l = randrange(1, n + 1)
        r = randrange(l, n + 1)
        print(l, r)


main()
