#!/usr/bin/env python3

def main():
    h = 2
    r = 16
    print(h, r)
    for i in range(r):
        for j in range(r):
            if i == j:
                print(0, end=' ')
            else:
                print(1, end=' ')
        print()

main()
