#!/usr/bin/env python3

import asyncio
from asyncio.subprocess import PIPE

async def main():
    pr_judge = await asyncio.create_subprocess_exec(
        './t_judge',
        stdin=PIPE, stdout=PIPE)
    pr_cans = await asyncio.create_subprocess_exec(
        './t_cans',
        stdin=PIPE)
    pr_judge.stdin.write('hello'.encode())
    await pr_judge.stdin.drain()
    pr_cans.stdin.write(b'hello')
    await pr_judge.stdin.drain()
    

asyncio.run(main())

