#!/usr/bin/env python3

import sys, argparse, os, re, subprocess
from bs4 import BeautifulSoup
from util import die, warn, postData

args = None
fKeep = None

diag=warn

# def get_submit_form(soup):
#     for ftag in soup.find_all('form'):
#         if ftag.find_all(attrs={'name': 'data.TaskScreenName'}):
#             ops = ftag.find_all('option');
#             if 'value' in ops[0].attrs:
#                 top_op = ops[0].attrs['value']
#             elif 'value' in ops[1].attrs:
#                 top_op = ops[1].attrs['value']
#             else:
#                 die('Failed to get the first language option.');
#             if top_op == '3003':
#                 jv = 'jv3'
#             elif top_op == '4001':
#                 jv = 'jv4'
#             elif top_op == '4101':
#                 jv = 'jv41'
#             elif top_op == '5001':
#                 jv = 'jv5'
#             else:
#                 die('Unknown judge version')
#             return (ftag, jv)
#     die('Failed to find submit form.')

def parse_problem_url(soup):
    for fhead in soup.find_all('head'):
        for fmeta in fhead.find_all('meta', attrs={'property': 'og:url'}):
            problem_url = fmeta.attrs['content']
            mo = re.match(r'(.*)/tasks/(.*)', problem_url)
            if not mo:
                die(f'Unexpected problem url: {problem_url}')
            return (mo[1], mo[2])
    die('Failed to find contest url.')
    

def check_code(prog):
    diag('Performing stest ...')
    cp = subprocess.run(['stest', '-p', prog])
    if cp.returncode != 0:
        die('stest failed.  Use --no-check to force submitting.')
    diag('stest done.')

def get_lang_info(srcName):
    mo = re.match(r'(?:./)*((.*)\.([^\.]+))$', srcName)
    if not mo:
        die(f'Failed to parse source name {srcName}')
    if not mo[3]:
        die(f'No extension in source name {srcName}')
    li = {'cc': {'prog': './' + mo[2], 'jv': '5001'},
          'py': {'prog': './' + mo[1], 'jv': '5055'},
          'rs': {'prog': 'cargo run --quiet', 'jv': '5054'},
          }
    if mo[3] not in li:
        die(f'Extension {mo[1]} is not supported.')
    return (li[mo[3]]['prog'], li[mo[3]]['jv'])

def main():
    global args, fKeep
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--no-check', action='store_true',
        help = 'submit the source without checking')
    parser.add_argument('-s', '--source', default='cans.cc', 
                        help='file to submit.  Default is cans.cc')
    args = parser.parse_args()

    (prog, langID) = get_lang_info(args.source)
    if not args.no_check:
        check_code(prog)

    with open('q.html', 'r', encoding='UTF-8') as fp:
        soup = BeautifulSoup(fp, 'lxml')
    (contest_url, problem_id) = parse_problem_url(soup)

    with open(args.source, 'r', encoding='UTF-8') as fp:
        code = fp.read()

    payload = {'data.TaskScreenName': problem_id,
               'data.LanguageId': langID,
               'sourceCode': code}
    url = contest_url + '/submit'
    diag('Submitting ...')
    r = postData(url, payload)
    diag('Done.')

main()
