#!/usr/bin/env python3

import os
import subprocess

template_json = '''{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "launch_gdb",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/cans",
            "args": ["<", "din_1.txt"],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }

    ]
}
'''

def main():
    dot_vsc = '.vscode'
    if not os.path.exists(dot_vsc):
        os.mkdir(dot_vsc)
        path = f'{dot_vsc}/launch.json'
        with open(path, 'w') as wfp:
            print(template_json, file=wfp)
    subprocess.run(['code', '.'])    


main()
