#!/usr/bin/env python3

from subprocess import run, PIPE, DEVNULL


def main():
    N = 10**7
    Rs = [0.1, 0.4, 0.7]
    datagen = './gen_coloring'
    rec = {'prog': './color_a', 'label': 'recursive'}
    nonrec = {'prog': './color_b', 'label': 'non-recursive'}
    datafile = 'in_coloring.txt'
    rep = 5
    for R in Rs:
        with open(datafile, 'w') as fp:
            cp = run(['./gen_coloring', str(N), str(R)], stdout=fp)
        for te in [rec, nonrec]:
            for i in range(rep):
                time_i = 0.0
                with open(datafile) as fp:
                    cp = run([te['prog']], stdin=fp, stdout=PIPE, stderr=DEVNULL)
                time_s = cp.stdout
                time_i += float(time_s)
            print(f'{te["label"]:15s}({R})  {time_i / rep:.3f}sec')
            

main()
