#!/usr/bin/env python3

import sys
from random import randrange;

N = int(sys.argv[1])
ratio = float(sys.argv[2])
M = int(N * ratio)

ss = set()

print(N, M)
for i in range(M):
    while True:
        x = randrange(1, N + 1)
        y = randrange(1, N + 1)
        if x == y:
            continue
        if x > y:
            x, y = y, x
        if (x, y) in ss:
            continue
        ss.add((x, y))
        print(x, y)
        break
