#!/usr/bin/env python3

from random import randrange


N = 3999
lst = list(range(1, N + 1))
print(N)
print(' '.join(map(str, lst)))
for i in range(2, N + 1):
    if i % 2 == 0:
        print(i - 1, i)
    else:
        print(i - 2, i)
