#!/usr/bin/env python3

import argparse, sys
from random import randrange, choice, shuffle

# Function generate() should yield test cases of type string repeatedly.
# E.g.,
#    def generate():
#        for x in range(1, 10):
#            for cdir in ['N', 'E', 'S', 'W']:
#                yield f'{x}\n{cdir}\n'
# or E.g.,
#    def generate():
#        while True:
#            x = randrange(1, 10)
#            cdir = choice(['N', 'E', 'S', 'W'])
#            case = f'''{x}
#    {cdir}
#    '''
#            yield case

def show_list(lst):
    return ' '.join([str(x) for x in lst])

def generate():
    while True:
        N = randrange(2, 10)
        K = randrange(1, 3*N+1)
        lst = list(range(1, N+1))
        shuffle(lst)
        cost = [randrange(-10, 10) for _ in range(N)]
        case = f'''{N} {K}
{show_list(lst)}
{show_list(cost)}
'''
        yield case

######################################################################
# Hope that you need not edit the following code.

end_mark = '^__=end=__^'
end_file_mark = '^__=end_file=__^'

def main():
    ap = argparse.ArgumentParser();
    ap.add_argument('-r', '--repeat', action='store_true',
                    help='Repeatedly generates cases',)
    args = ap.parse_args()

    try:
        if args.repeat:
            for s in generate():
                print(s.rstrip())
                print(end_mark)
            print(end_file_mark)
        else:
            for (i, s) in enumerate(generate()):
                print(s.rstrip())
                print(end_mark)
                if (i == 4):
                    break
    except BrokenPipeError as e:
        # print('caught: BrokenPipeError', file=sys.stderr)
        pass

main()
