./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
./cans < din_1.txt
