#!/usr/bin/env python3

# Game Solver
#   This code segment judges which player wins at a given position in a game
#   like NIM.   It is assumed that a player loses when he cannot move.
#
#   You should define functions moves and mkkey:
#
#     moves(v) returns the list of all positions movable from position v
#     mkkey(v) returns a hashable value for v.  If v is already hashable,
#              the identity function is OK.
#
#   Then, function judge(v) returns True if the second player wins at v,
#   and returns False if the first player wins.


# --- You should modify code from HERE(, and the main function).

# (The following code is for NIM.)

n = 3

#     moves(v) returns the list of all positions movable from position v
def moves(v):
    (x, ss) = v;
    ret = []
    for i in range(n):
        if i == x or ss[i] == 0:
            continue
        ts = ss[:]
        ts[i] -= 1;
        ret.append((i, ts))
    return ret

#     mkkey(v) returns a hashable value for v.  If v is already hashable,
#              the identity function is OK.
def mkkey(v):
    (x, ss) = v
    return (x, ss[0], ss[1], ss[2])

# --- You should modify code to HERE.


# You need not edit function judge().
memo = {}
def judge(v):
    k = mkkey(v)
    if k not in memo:
        result = True
        for w in moves(v):
            if judge(w):
                result = False
                break
        memo[k] = result
    return memo[k]

def main():
    # Prints the winning places for the second player.
    m = 6
    for i in range(m):
        for j in range(m):
            for k in range(m):
                # for p in range(3):
                p = -1
                if judge((p, [i, j, k])):
                    print(p, " ", i,j,k)


main()
