#!/usr/bin/env python3

import argparse, sys
from random import randrange, choice, shuffle

def show_list(lst):
    return ' '.join(map(str,lst))

# Function generate() should yield test cases of type string repeatedly.
# E.g.,

def generate_seq():
    for x in range(1, 10):
        for cdir in ['N', 'E', 'S', 'W']:
            yield f'{x}\n{cdir}\n'

# or E.g.,

def generate_random():
    while True:
        n = randrange(2, 7)
        link = [[False for _ in range(n)] for _t in range(n)]
        for i in range(1, n):
            j = randrange(i)
            link[i][j] = True
            link[j][i] = True
        cnt = 0
        for i in range(n):
            for j in range(i + 1, n):
                if randrange(10) < 3:
                    link[i][j] = True
                    link[j][i] = True
                if link[i][j]:
                    cnt += 1
        case = f'{n} {cnt}\n'
        for i in range(n):
            c = randrange(1, 100)
            r = randrange(1, n + 1)
            case += f'{c} {r}\n'
        for i in range(n):
            for j in range(i + 1, n):
                if link[i][j]:
                    case += f'{i + 1} {j + 1}\n'
        yield case

# generate = generate_seq
generate = generate_random

######################################################################
# Hope that you need not edit the following code.

end_mark = '^__=end=__^'
end_file_mark = '^__=end_file=__^'

def main():
    ap = argparse.ArgumentParser();
    ap.add_argument('-r', '--repeat', action='store_true',
                    help='Repeatedly generates cases',)
    args = ap.parse_args()

    try:
        if args.repeat:
            for s in generate():
                print(s.rstrip())
                print(end_mark)
            print(end_file_mark)
        else:
            for (i, s) in enumerate(generate()):
                print(s.rstrip())
                print(end_mark)
                if (i == 4):
                    break
    except BrokenPipeError as e:
        # print('caught: BrokenPipeError', file=sys.stderr)
        pass

main()
