#!/usr/bin/env python3

from random import randrange

def main():
    N = 20000
    print(N)
    for i in range(N):
        # print(randrange(1, 100001), end = ' ')
        print(60060, end = ' ')
    print()
    for i in range(2, N + 1):
        print(i//2, i)


main()
