#!/usr/bin/env python3

from subprocess import run, PIPE, DEVNULL

tot = 0
for seq in range(0, 10):
    with open(f'in/{seq:04d}.txt', encoding='utf-8') as fp:
        cp = run(['./cans'],
                 encoding='utf-8',
                 stdin=fp,
                 stderr=DEVNULL,
                 stdout=PIPE)
    val = int(cp.stdout.split('\n')[0])
    tot += val
print(tot)



