#!/usr/bin/env python3

import argparse, sys
from random import randrange, choice, shuffle, choices
import math

def main():
    Q = 10**6
    N = int(math.sqrt(Q))
    print(N, Q)
    conn = set()
    for q in range(Q):
        while True:
            [t] = choices([1, 2, 3], [3, 10, 2])
            x = randrange(0, N)
            y = randrange(0, N)
            if x == y:
                continue
            if t == 1 and (x, y) in conn:
                continue
            if t == 2 and (x, y) not in conn:
                continue
            break
        print(t, x, y)
        if t == 1:
            conn.add((x, y))
            conn.add((y, x))
        if t == 2:
            conn.remove((x, y))
            conn.remove((y, x))

main()
