#!/usr/bin/env python3

from random import randrange

def main():
    lim = int(1e5)
    rec = [0] * lim
    sz = 0
    # dsz = 100
    dsz = 400000
    print(dsz)
    for i in range(dsz):
        while True:
            t = randrange(1, 3)
            # t = randrange(1, 5)
            x = randrange(lim)
            if not (t == 4 and sz == 0):
                break
        if t == 1:
            print(t, x)
            if rec[x] == 0:
                rec[x] = 1
                sz += 1
        elif t == 2:
            print(t, x)
            if rec[x] == 1:
                rec[x] = 0
                sz -= 1
        elif t == 3:
            print(t, x)
        elif t == 4:
            z = randrange(sz)
            print(t, z)

main()
