#!/usr/bin/env python3

from random import randrange


def main():
    N = 10**6
    K = 8 * 10**5
    print(N, K)
    for _ in range(K):
        while True:
            a = randrange(N)
            b = randrange(N)
            if a != b:
                print(a, b)
                break


main()
