#!/usr/bin/env python3

import argparse, sys
from random import randrange, choice, shuffle

def show_list(lst):
    return ' '.join(map(str,lst))

# Function generate() should yield test cases of type string repeatedly.
# E.g.,

def generate_seq():
    for x in range(1, 10):
        for cdir in ['N', 'E', 'S', 'W']:
            yield f'{x}\n{cdir}\n'

# or E.g.,

def generate_random():

    # This is the function you should edit.
    # You can use prcase() to print the value to the case
    def onecase():
        def collide(x, y):
            if x == sx and y == sy:
                return True
            if x == gx and y == gy:
                return True
            for i in range(n):
                if x == X[i] and y == Y[i]:
                    return True
        h = 10
        w = 10
        n = 5
        sx = randrange(1, h + 1)
        sy = randrange(1, w + 1)
        gx = -1
        gy = -1
        X = [-1] * n
        Y = [-1] * n
        while True:
            x = randrange(1, h + 1)
            y = randrange(1, w + 1)
            if not collide(x, y):
                (gx, gy) = (x, y)
                break
        for i in range(n):
            while True:
                x = randrange(1, h + 1)
                y = randrange(1, w + 1)
                if not collide(x, y):
                    (X[i], Y[i]) = (x, y)
                    break
        prcase(h, w, n)
        prcase(sx, sy)
        prcase(gx, gy)
        for i in range(n):
            prcase(X[i], Y[i])

    # do not edit
    def prcase(*args):
        nonlocal case
        for i, a in enumerate(args):
            if i > 0:
                case += ' '
            case += str(a)
        case += '\n'

    # do not edit
    while True:
        case = ''
        onecase()
        yield case

# generate = generate_seq
generate = generate_random

######################################################################
# Hope that you need not edit the following code.

end_mark = '^__=end=__^'
end_file_mark = '^__=end_file=__^'

def main():
    ap = argparse.ArgumentParser();
    ap.add_argument('-r', '--repeat', action='store_true',
                    help='Repeatedly generates cases',)
    args = ap.parse_args()

    try:
        if args.repeat:
            for s in generate():
                print(s.rstrip())
                print(end_mark)
            print(end_file_mark)
        else:
            for (i, s) in enumerate(generate()):
                print(s.rstrip())
                print(end_mark)
                if (i == 4):
                    break
    except BrokenPipeError as e:
        # print('caught: BrokenPipeError', file=sys.stderr)
        pass

main()
